rust-lang/rustc_codegen_gcc

LICENSE-APACHE, NOTICE
=> Add attribution

Readme.md
=> Add motivation in readme

test.sh
LD_LIBRARY_PATH is used at runtime whereas LIBRARY_PATH is used during linking.
Without it, I get:
= note: /usr/bin/ld: cannot find -lgccjit
collect2: error: ld returned 1 exit status
during the `cargo rustc` in `test.sh`
=> Use LIBRARY_PATH to have ld look for libgccjit at link time

.github/workflows/main.yml
It doesn't exist anymore causing CI to fail
=> Remove -Zrun_dsymutil=no

Cargo.toml, src/base.rs
Fix #44.
@dkm : It could be tricky to get the results, not only because they'll be in `/tmp`, but also because of CGUs: you'll have multiple temp directory to look at.
=> Send llvm-args to libgccjit

Readme.md
The repository link for cloning in the README was wrong, there are still some wrong links pointing to the [antoyo](https://github.com/antoyo) profile, but it can't be fixed as the additional repositories haven't moved for the organization yet.
=> fix: gh origin on readme

src/asm.rs
Also, we no longer translate `ax`, `bx`, `cx` etc. register to `a`, `b`, `c` constraints and just create register variables for them. It's easier this way and should work just as good..
=> Impove handling of registers in inline asm

src/lib.rs
rustc_interface already calls it for you.
=> Remove unnecessary report_symbol_names call

cargo.sh, prepare_build.sh, rust-toolchain, src/consts.rs, src/declare.rs, test.sh, tests/run/assign.rs, tests/run/int_overflow.rs, tests/run/mut_ref.rs, tests/run/operations.rs
This is a fix for the environment variable issue I reported in a PM.
Previously foreign statics would actually cause a local static to be defined and exported. This issue was found because std::env::vars() was found to return no env vars despite many being defined. This was caused by libstd importing environ as foreign static. The accidental definition of environ caused libstd to read a null pointer which was interpreted as there being no environment variables at all.
I also move rustup component installation to rust-toolchain This allows cargo check to function correctly without having to first
run prepare_build.sh. cg_clif has been using rust-toolchain too for a while now.
=> Correctly import foreign statics

Cargo.lock, patches/0023-core-Ignore-failing-tests.patch, src/consts.rs, src/context.rs
=> Support upgrading the alignment of a global variable

src/base.rs
This puts every function and data object in their own section. This allows the linker to omit unused functions and data objects with `--gc-sections`.
On linux this shrinks a hello world binary without optimizations (neither sysroot nor binary) from 17MB to 13MB. It shrinks a hello world binary with only sysroot optimizations from 14MB to 13MB. For comparison cg_llvm produces a 3.5MB debug mode hello world binary with an optimized sysroot. Cg_clif produces a 10MB debug mode hello world binary without an optimized sysroot.
Fixed https://github.com/rust-lang/rustc_codegen_gcc/issues/117
=> Support -Zfunction-sections

Readme.md
I hope this is correct, at least it makes it build again for me.
=> README: Add compiler-rt cloning step

patches/0024-core-Disable-portable-simd-test.patch, rust-toolchain, src/archive.rs, src/builder.rs, src/consts.rs, src/type_of.rs
Please don't squash this PR when merging.
=> Rustup to rustc 1.61.0-nightly (4b043faba 2022-02-24)

Cargo.lock, src/base.rs, src/builder.rs, src/intrinsic/mod.rs
This is necessary for bootstrapping rustc as compiling rustc with -Cpanic=abort is rather hard if at all possible. This does not implement actual unwinding on panics.
=> Support -Cpanic=unwind without unwinding

src/consts.rs, src/context.rs, src/declare.rs
They aren't be referenced outside of the current cgu anyway. This should make optimizations a bit more effective.
=> Don't export global allocs which are not statics

test.sh
=> Stop removing the llvm-asm tests in test.sh since they don't exist anymore

build_sysroot/Cargo.toml, example/mini_core.rs, src/type_of.rs
Applying the fix from https://github.com/rust-lang/rust/pull/94043
=> Fix ice in box alloc

build.sh
This PR adds a functionality to `build.sh` to build sysroot with optimization enabled, separately from the codegen. Supersedes #142.
=> Add `--release-sysroot` flag to `build.sh`

cargo.sh
This was a workaround for compiling proc macros resulting in an abi
incompatibility. By passing --target proc macros will be built by the
llvm backend. This is no longer necessary as the abi incompatibility has
since been fixed.
=> Don't pass --target in cargo.sh

src/intrinsic/mod.rs, tests/run/int.rs
=> Implement `saturating_{add, sub}` for non-native integer types

src/asm.rs
Cherry-picked from <https://github.com/yvt/rustc_codegen_gcc/commit/5f8660156af3721f79b96d084c0e28bf421ea92f>
=> Don't emit `.intel_syntax` for non-x86 targets

Cargo.toml, src/asm.rs, tests/lang_tests_common.rs, tests/lang_tests_debug.rs, tests/lang_tests_release.rs, tests/run/int_overflow.rs
Updates `<Builder as AsmBuilderMethods>::codegen_inline_asm` to convert `sym` operands into GCC `"X" (&func_or_static)` input operands to indicate the dependency on the referenced symbols and prevent them from being eliminated.
Fixes #157.
=> Add inline assembly `sym` operands as GCC input operands

Cargo.lock, src/consts.rs
This PR adds `const` qualification to the types of immutable statics to allow them to be placed in a read-only section.
Fixes #161.
```rust
#[no_mangle]
pub extern "C" fn ultimate_answer_concise() -> u32 {
const CANDIDATES: &[u32] = &[41, 42, 43];
CANDIDATES[1]
}
```
```
Before:
0000000000001100 <ultimate_answer>:
1100:       48 8d 05 19 2f 00 00    lea    0x2f19(%rip),%rax        # 4020 <ultimate_answer_concise+0x2f10>
1107:       c3                      ret
1108:       0f 1f 84 00 00 00 00    nopl   0x0(%rax,%rax,1)
110f:       00
After:
0000000000001110 <ultimate_answer_concise>:
1110:       b8 2a 00 00 00          mov    $0x2a,%eax
1115:       c3
```
=> Define immutable statics with const qualified types

.github/workflows/ci.yml, tools/check_intrinsics_duplicates.py
This a follow-up of https://github.com/rust-lang/rustc_codegen_gcc/pull/181.
It checks for duplicated intrinsics between the ones generated automatically and the ones listed just before them in the "manual" code.
I committed the tool to do so and added a github action pass for it.
=> Remove duplicated intrinsics and add check

failing-ui-tests.txt, failing-ui-tests12.txt, src/builder.rs, src/intrinsic/simd.rs, src/type_.rs
Implements the following simd reduction intrinsics:
- `simd_reduce_add_ordered`
- `simd_reduce_mul_ordered`
- `simd_reduce_min_nanless`
- `simd_reduce_max_nanless`
- `simd_reduce_xor`
- `simd_reduce_any`
- `simd_reduce_all`
Also fixes the ordering of `simd_reduce_min` and `simd_reduce_max`, which were tested to be flipped.
Both `simd_reduce_min_nanless` and `simd_reduce_max_nanless` are identical to their non-nanless variants for the time being.  An attempt was made at a more optimal codegen solution based on `vector_reduce_op`.  However, this approach ran into masking issues for floating-point vector types,which appears to be broken for the same reason that comparison operations such as `simd_lt` are broken for floating-point vector types.  More investigation is required, however, to …
=> simd: Implement missing reduction intrinsics

failing-ui-tests.txt, failing-ui-tests12.txt, src/builder.rs, src/intrinsic/simd.rs
This implements simd_fmin/fmax in a largely-optimal method.
Signed-off-by: Andy Sadler <andrewsadler122@gmail.com>
=> simd: implement simd_fmin/fmax

failing-ui-tests.txt, failing-ui-tests12.txt, src/builder.rs
This fixes some tests that needed vector element extraction.
Signed-off-by: Andy Sadler <andrewsadler122@gmail.com>
=> simd: impl extract_element for vector types

failing-ui-tests.txt, src/intrinsic/simd.rs
Implements the intrinsics required to pass float-math-pass and libm_std_can_float ui tests.
Signed-off-by: Andy Sadler <andrewsadler122@gmail.com>
=> simd: implement float math intrinsics

.github/workflows/release.yml, src/back/write.rs, src/base.rs, src/builder.rs, src/int.rs, test.sh
=> Add CI tests with a sysroot compiled in release mode

failing-ui-tests.txt, failing-ui-tests12.txt, src/intrinsic/simd.rs
The method context.convert_vector, added to libgccjit for `simd_cast`, appears to give the correct behavior for `simd_as`.  Instead of special-casing `simd_as`, re-use `simd_cast`'s impl for `simd_as`.
Signed-off-by: Andy Sadler <andrewsadler122@gmail.com>
=> simd: enable simd_as intrinsic

.github/workflows/ci.yml, .github/workflows/release.yml
Recent Github actions runs display the following warning:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout, actions/cache, actions/cache, actions/cache, actions/cache, actions-rs/cargo, actions/cache, actions/cache, actions/cache, actions/cache, actions/checkout, actions/checkout
```
This PR fixes this issue by bumping actions dependencies to use new releases based on node16.
This PR also remove cargo cache fixups that are not needed anymore.
The failing jobs (`--test-failing-rustc`) are the same as on main so not related to this PR.
=> Bump Github actions

.github/workflows/ci.yml, src/asm.rs, src/base.rs, test.sh
Part of https://github.com/rust-lang/rustc_codegen_gcc/issues/60.
=> Add missing register class conversion for inline asm

.github/workflows/release.yml, patches/0001-Disable-examples.patch, src/base.rs, src/lib.rs
=> Run stdarch tests in the CI

src/consts.rs
This is the cg_gcc counterpart to https://github.com/rust-lang/rust/pull/81664. Best reviewed with whitespace changes ignored.
=> Avoid a hir access inside get_static

src/allocator.rs
This deduplicates some logic and makes it easier to follow what wrappers are produced. In the future it may allow moving the code to determine which wrappers to create to cg_ssa.
=> Extract a create_wrapper_function for use in allocator shim writing

Cargo.lock, src/attributes.rs
Depends on https://github.com/antoyo/gcc/pull/22 and on https://github.com/antoyo/gccjit.rs/pull/21.
Will also need to update gccjit dependency once merged.
=> Add support for "ffi_const" function attribute

src/abi.rs
`NoAlias` (and its translation into `__restrict__`) should only be applied if optimization is enabled (as does `cg_llvm`). This PR fixes that.
=> Only apply NoAlias attribute if optimization is enabled

Cargo.lock, failing-ui-tests.txt, failing-ui-tests12.txt, src/builder.rs, src/gcc_util.rs, test.sh, tests/run/gep.rs
=> Fix gep on pointers to non-number

src/abi.rs, src/declare.rs, src/intrinsic/mod.rs, src/type_of.rs
Based on https://github.com/antoyo/gcc/pull/28 and on https://github.com/antoyo/gccjit.rs/pull/23.
=> Add support for NonNull function attribute

src/intrinsic/mod.rs
In the current implementation, the gcc backend of rustc currently emits the
following for a function that implements popcount for a u32 (x86_64 targeting
AVX2, using standard unix calling convention):
popcount:
mov     eax, edi
and     edi, 1431655765
shr     eax
and     eax, 1431655765
add     edi, eax
mov     edx, edi
and     edi, 858993459
shr     edx, 2
and     edx, 858993459
add     edx, edi
mov     eax, edx
and     edx, 252645135
shr     eax, 4
and     eax, 252645135
add     eax, edx
mov     edx, eax
and     eax, 16711935
shr     edx, 8
and     edx, 16711935
add     edx, eax
movzx   eax, dx
shr     edx, 16
add     eax, edx
ret
Rather than using this implementation, gcc could be told to use Wenger's
algorithm.  This would give the same function the following implementation:
popcount: …
=> optimize popcount implementation

src/intrinsic/mod.rs
Don't fall back on breaking apart the popcount operation if 128-bit integers are natively supported.
=> optimize u128/i128 popcounts further

Readme.md, build_system/src/build.rs, build_system/src/config.rs
=> Fix to be able to use a target specification JSON file and document the process

Readme.md
=> Fix build instructions

failing-ui-tests.txt, failing-ui-tests12.txt, src/builder.rs, src/int.rs, src/intrinsic/simd.rs
This implements/fixes the following intrinsics:
- `simd_bswap`
- `simd_frem`
- `simd_bitreverse`
- `simd_ctlz`
- `simd_cttz`
- `simd_neg`
These were the remaining intrinsics from the `simd/generic-arithmetic-pass.rs` ui test, which should now pass for a patched libgccjit.  However, [it seems not to compile against a non-patched libgccjit][1], so leave it disabled there for now.
[1]: https://github.com/sadlerap/rustc_codegen_gcc/actions/runs/6820180639/job/18548672444#step:15:4375
=> simd: implement missing intrinsics from simd/generic-arithmetic-pass.rs

.github/workflows/ci.yml, .github/workflows/failures.yml, .github/workflows/gcc12.yml, .github/workflows/m68k.yml, .github/workflows/release.yml, .github/workflows/stdarch.yml
actions-rs is deprecated. Switch to using the preinstalled rustup to install the toolchain, and https://github.com/Swatinem/rust-cache to configure cacheing.
https://github.com/dtolnay/rust-toolchain cannot be used because it does not respect `rust-toolchain`.
I believe there isn't any need to run `cargo build` separately anymore since there are no longer error annotations.
Fixes https://github.com/rust-lang/rustc_codegen_gcc/issues/381
=> Switch from actions-rs to preinstalled rustup

build_system/src/test.rs
`build_system/src/test.rs` generates a `config.toml` that contains a path directly to (what should be) the appropriate rustc binary. However, it incorrectly assumed rustup stores the rustc binaries in `~/.rustup`. In actuality, rustup first checks the [environment variable](https://rust-lang.github.io/rustup/environment-variables.html) `RUSTUP_HOME`, and defaults to `~/.rustup` if the variable is not set. Now `build_system/src/test.rs` uses the correct path.
If there is a more idiomatic way to encode this please let me know and I'll fix it.
=> Honor `$RUSTUP_HOME`

build_system/src/test.rs
=> Improve iterator for files suppression

build_system/src/test.rs
GitHub may not necessarily be accessible in some conditions/locations. Switching to a shallow clone can significantly reduce the time for cloning rust from GitHub.
=> Use shallow clone in test.rs to reduce cloning overhead

build_system/src/test.rs
Reverts rust-lang/rustc_codegen_gcc#432
After further discussions with @antoyo, we came to the conclusion that rather than using extra complex commands, downloading the whole git history was taking more disk space but was simpler to maintain as a whole. Like I said, I'm not a big fan of `--depth` because of issues I encountered with it in the past too so at least it's always that off my mind.
Thanks in  any case @tempdragon!
=> Revert "Use shallow clone in test.rs to reduce cloning overhead"

Cargo.toml
Based on the comments in #428, it may be a good idea to add this option to `Cargo.toml` .
Hopefully I didn't misunderstand the suggestions from @antoyo & @sadlerap .
Thanks in advance.
=> feat(Cargo.toml): Set `rustc_private` to `true` to allow lsp parsing

src/intrinsic/simd.rs, tests/failing-ui-tests.txt, tests/failing-ui-tests12.txt
Work around an issue where usize and isize can sometimes (but not always) get canonicalized to their corresponding integer type.  This causes shuffle_vector to panic, since the types of the vectors it got passed aren't the same.
Also insert a cast on the mask element, since we might get passed a signed integer of any size, not just i32.  For now, we always cast to i32.
=> fix tests/ui/simd/issue-89193.rs and mark as passing

build_system/src/build.rs, build_system/src/config.rs, build_system/src/test.rs
Bug detected in https://github.com/rust-lang/rust/pull/121390.
=> Remove unused `feature = "master"` cfg in build_system

Cargo.lock, Cargo.toml, tests/lang_tests_common.rs
=> Update lang_tester so that panicking in a test results in the test failing

messages.ftl, src/errors.rs
Detected by https://github.com/rust-lang/rust/pull/121752
=> Remove unused structs

src/allocator.rs, src/asm.rs, src/back/lto.rs, src/consts.rs, src/debuginfo.rs, src/intrinsic/mod.rs, src/lib.rs, src/mono_item.rs, src/type_.rs, tests/lang_tests_common.rs
NOTE: This is generated by `cargo clippy --fix --allow-dirty  -- -D --warnings `, and warnings are ignored by the clippy.
To pass the whole clippy test, more work is needed. For consistency, you may as well generate one yourself and then fix the warnings in your series.
// This is probably my last commit to cg_gcc in a month. Happy coding!
=> fix(fmt/style): Clippy-generated Code Correction

.github/workflows/ci.yml, src/asm.rs, src/attributes.rs, src/back/lto.rs, src/back/write.rs, src/base.rs, src/builder.rs, src/callee.rs, src/common.rs, src/consts.rs, src/context.rs, src/debuginfo.rs, src/declare.rs, src/int.rs, src/intrinsic/llvm.rs, src/intrinsic/mod.rs, src/intrinsic/simd.rs, src/lib.rs, src/type_of.rs
1. I don't know if you are interested in merging this half-generated(if not fully) commit. If not, feel free to close it. Everything is generated if not mentioned.
2. I do apologize for a likely delay in answering the reviews.
3. I renamed the methods  `from_low_high_rvalues` and `from_low_high` in tempdragon/rustc_codegen_gcc@a7d39b852a5ad19b11781c18b59d38dc6ef92932
4. All life time related modifications were done by using  `cargo clippy --fix --lib -p rustc_codegen_gcc --allow-dirtyxs`, as is done in tempdragon/rustc_codegen_gcc@ad97b8c061e6f39a52daaf036c9721e17510c30c. However, since I am not an expert in lifetime, I can't guarantee its correctness(But it passed the workflow anyway.)
5. In tempdragon/rustc_codegen_gcc@d2cda90e4ecb32cbf7be08d166daa78b5dbed819, the `shift` was removed …
=> Clippy related fixes

build_system/src/build.rs
=> Fix passing custom CG_RUSTFLAGS when building sysroot

src/abi.rs, tests/failing-ui-tests.txt
=> Fix PassMode::Indirect with params

build_system/src/prepare.rs, doc/tips.md
This change allows users to specify a custom directory from which to copy the sysroot source code instead of being forced to use the `rust-src` provided with the `rustup` toolchain. The path is passed to `--sysroot-source` during the `prepare` stage, like so:
```
./y.sh prepare --sysroot-source /path/to/custom/source
```
This removes a pain point for using rustc_codegen_gcc while creating and testing support for new platforms with architectures without LLVM support.
=> Modify build_system's prepare stage to allow for custom sysroot source path

src/attributes.rs, src/builder.rs, src/intrinsic/llvm.rs
Combined with https://github.com/rust-lang/gcc/pull/52, this makes some progress for issue #242.
=> Some fixes for aarch64

.github/workflows/ci.yml, .github/workflows/failures.yml, .github/workflows/release.yml
=> Download artifacts from `rust-lang/gcc` instead of old `antoyo/gcc`

build_system/src/utils.rs
=> Stop swallowing signals in build_system when running sub-commands

Readme.md
Added more env vars to the Readme.md file.
=> adding more env vars

src/intrinsic/simd.rs, tests/failing-ui-tests.txt
This adds support for the simd variants of the pointer provenance intrinsics, which are `simd_cast_ptr`, `simd_expose_addr`, and `simd_from_exposed_addr`.
The preconditions for each intrinsic are adapted from `rustc_codegen_llvm` to preserve compatibility.  Each of these intrinsics are implemented as calling the non-simd variant of each intrinsic on each lane.
This is enough to enable the UI test `ui/simd/intrinsic/ptr-cast.rs` to pass.
=> simd: implement pointer provenance intrinsics

build_system/src/config.rs
Alternative to #528, I find it easier to show what I meant rather than tell.
Fixing up the download URL while at it. 
fixes #527
=> prevent libgccjit.so download on unsupported os/arch

src/builder.rs
This makes the generated code cleaner so it's easier to debug.
=> Remove dummy value locals for function ptr calls

src/debuginfo.rs, src/lib.rs, tools/generate_intrinsics.py
I understand if `extract_instrinsics_from_llvm` change is too intrusive a change... let me know!
=> Fix some typos

.github/workflows/ci.yml, .github/workflows/failures.yml, .github/workflows/gcc12.yml, .github/workflows/m68k.yml, .github/workflows/release.yml, .github/workflows/stdarch.yml
Required for using Node.js 20.x in CI
* Changelog for actions/checkout@v4 https://github.com/actions/checkout/blob/main/CHANGELOG.md?rgh-link-date=2024-09-04T18%3A38%3A10Z#v400
* GitHub Blog post https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
Refs: https://github.com/rust-lang/rust/pull/130124#issuecomment-2336871149
=> ci: bump actions/checkout to v4

tests/lang_tests_common.rs
`config.toml` isn't there (and shouldn't be there) by default, which makes this part of the code to fail on compilation, and that fails upstream rust to bootstrap with certain commands (e.g., `x fix`). This change should fix that problem.
=> stabilize `lang_tests_common` config parsing logic

.github/workflows/ci.yml, .github/workflows/gcc12.yml, .github/workflows/m68k.yml, .github/workflows/release.yml, .github/workflows/stdarch.yml
There shouldn't be a need to run all CI jobs on all pushes.
=> Remove duplicated CI triggers

src/context.rs
As discussed on chat, there currently is the bug where certain suffixes are interpreted by the (m68k) assembler.
Example: `move.l #global.w,-44(%fp)`
`.w` is interpreted by the assembler as a size hint for #global.
=> Make globals always have 2+ chars as suffix

build_system/src/test.rs
fixes #622 
The problem is with escaping the `--compiletest-rustc-args` argument. Use of `\` and `"` or even `'` does not work because of how this string is eventually used.
With this change I can actually run the asm tests
```
failures:
[assembly] tests/assembly/asm/global_asm.rs
[assembly] tests/assembly/asm/inline-asm-avx.rs
test result: FAILED. 0 passed; 2 failed; 50 ignored; 0 measured; 465 filtered out; finished in 57.76ms
Some tests failed in compiletest suite=assembly mode=assembly host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
help: ignored 1 up-to-date test; use `--force-rerun` to prevent this
```
If it's useful I can re-enable this test in `run_all`, but only 2 tests actually run (the rest is ignored) and those both fail right now.
=> fix backslashes in path used for `asm_tests`

src/builder.rs, src/intrinsic/llvm.rs
=> remove some intrinsics

Cargo.lock, Cargo.toml, src/abi.rs, src/context.rs, src/declare.rs, src/lib.rs
=> Support sysv64 and ms ABIs

src/asm.rs, tests/run/asm.rs
fixes https://github.com/rust-lang/rustc_codegen_gcc/issues/485
I believe (see the issue) that the `b` suffix can just be trimmed, without causing invalid behavior.
I also refactored a bit to reduce the level of nesting, given that we probably need much more logic here to support more register classes that don't translate 1-to-1 between llvm and gcc. Hopefully the rustc assembly tests will guide us towards the edge cases.
=> support `reg_byte` registers

triagebot.toml
This PR enables [`[no-mentions]`](https://forge.rust-lang.org/triagebot/no-mentions.html) and [`[issue-links]`](https://forge.rust-lang.org/triagebot/issue-links.html) from rustbot in `triagebot.toml`.
Related to https://github.com/rust-lang/team/pull/1790
cc @GuillaumeGomez @antoyo
=> Enable `[no-mentions]` and `[issue-links]` in `rustbot`

CONTRIBUTING.md, Readme.md
Follow-up of rust-lang/rustc_codegen_gcc#586.
=> Clean up docs

.gitattributes
This solves rust-lang/rustc_codegen_gcc#658
Also added a line to treat `Cargo.lock` as a text file and normalize eol.
=> Added a .gitattributes file for showing cargo.lock diffs

Cargo.toml, build_system/Cargo.toml, build_system/src/main.rs, build_system/src/utils.rs, src/back/lto.rs, src/back/write.rs, src/consts.rs, src/debuginfo.rs, src/declare.rs, src/lib.rs, tests/lang_tests_common.rs
Fixes rust-lang/rustc_codegen_gcc#662.
=> Switch to 2024 edition and remove `let_chains` feature

example/mini_core.rs, src/builder.rs, tests/run/switchint_128bit.rs
Due to a libgccjit limitation, 128 bit switches are currently not supported.
As a workaround, this PR:
1. Detects switches on 16 byte(128 bit) values.
2. Replaces such switches with an "if ladder".
Effectively, we turn this:
```rust
let val = black_box(64_u128);
match val {
0 => return 1,
1 => return 2,
64 => (),
_ => return 3,
}
```
Into this:
```rust
let val = black_box(64_u128);
if val == 0{
return 1;
}
else if val == 1{
return 2;
}
else if val ==   64 {
} else {
return 3; 
}
```
This is less efficient than a switch, but it **only** applies to previously unsupported edge case: 128 bit switches. So, the small perf penalty is acceptable in this case.
Besides that, this PR contains a regression test for this issue, and a few tiny changes to minicore. 
1. Added support for the `black_box` …
=> Add a workaround for 128 bit switches

src/attributes.rs, tests/run/always_inline.rs
Fixes https://github.com/rust-lang/rustc_codegen_gcc/issues/599. 
Instead of always translating `#[inline(always)]`(which is a *hint*) to `FnAttribute::AlwaysInline`(which makes inlining mandatory), we now do so only for functions which don't call any functions with the  `#[inline(always)]` or the rustc force inline attribute.
In cases where  `#[inline(always)]` is applied to a function which *might* be recursive, it is demoted to `#[inline]` instead. 
This breaks the cycle, and prevents libjitgcc errors. 
The regression test checks for direct and indirect recursion.
=> Fixed a recursive inling bug, added a test for it

src/allocator.rs
Fixes rust-lang/rustc_codegen_gcc#674.
With this change we now have:
```asm
000000000000505f <_RNvCsee83jQymicr_7___rustc26___rust_alloc_error_handler>:
505f:       55                      push   %rbp
5060:       48 89 e5                mov    %rsp,%rbp
5063:       48 83 ec 10             sub    $0x10,%rsp
5067:       48 89 7d f8             mov    %rdi,-0x8(%rbp)
506b:       48 89 75 f0             mov    %rsi,-0x10(%rbp)
506f:       48 8b 55 f0             mov    -0x10(%rbp),%rdx
5073:       48 8b 45 f8             mov    -0x8(%rbp),%rax
5077:       48 89 d6                mov    %rdx,%rsi
507a:       48 89 c7                mov    %rax,%rdi
507d:       e8 58 09 00 00          call   59da <_RNvCsee83jQymicr_7___rustc9___rdl_oom>
5082:       c9                      leave
5083:       c3 …
```
=> Add missing `add_eval` to generate `__rdl_oom` in the alloc error handler

src/common.rs, src/consts.rs, src/context.rs
This PR changes a few things.
First of all, it caches ConstAllocations, ensuring that for a given ConstAllocation(or one an identical one with a different aligement), you will get the exact same Rvalue.
This allows us to simplify the deduplication code in `static_addr_of`, and remove the formating (which caused memory leaks). 
Additonally, this allows constant byte sequences to *sometimes* be represented in a more compact fashion. From a few checks, it looks like ~80 % of constant byte sequences can be optimized this way.
=> Changes to constant handling - faster deduplication, more compact represtntation

src/builder.rs, src/context.rs, tests/run/packed_u128.rs
This PR fixes the segfault caused by packed structs containing u128 / i128.  https://github.com/rust-lang/rustc_codegen_gcc/issues/683
I also added a test to detect any regressions like this in the future.
=> Fix to 128 bit int unaligned loads

.github/workflows/ci.yml, .github/workflows/failures.yml, .github/workflows/m68k.yml, .github/workflows/release.yml, .github/workflows/stdarch.yml, CONTRIBUTING.md, build_system/src/test.rs
Added a new option to `./y.sh test`: ` ./y.sh test --cargo-tests`.
When this option is selected, `y.sh` will build & test minicore(it is a dependency). After that, it will simply call `cargo test` with the selected environment flags.  
For now  ` ./y.sh test --cargo-tests`  ignores `RUSTFLAGS`. 
Normally, `RUSTFLAGS` contain the `-Zcodegen-backend` option, which would make `cg_gcc` rebuild itself. This is undesirable, and ignoring `RUSTFLAGS` altogether was simply the easiest option. 
In the future, we maybe could filter out `-Zcodegen-backend`, and keep the rest of the flags intact.
=> modifed y.sh to allow for running cargo tests.

src/asm.rs
A tiny patch adding the very basic support for explicit registers in ARM/AArch64 assembly.
=> Added some bare-bones support for explict registers in ARM inline assembly

src/lib.rs
The tempfile library has deprecated `TempDir::into_path()`, replacing it by `TempDir::keep()` starting version 3.3. It leads to the following warnings which you can find in the [CI logs](https://github.com/rust-lang/rustc_codegen_gcc/actions/runs/15564268760/job/43824248563#step:8:54):
```rust
warning: use of deprecated method `tempfile::TempDir::into_path`: use TempDir::keep()
--> src/lib.rs:211:38
|
211 |             let temp_file = temp_dir.into_path().join("result.asm");
```
=> Use `tempfile::TempDir::keep()` instead of deprecated `into_path()`

.github/workflows/ci.yml, .github/workflows/release.yml, build_system/src/test.rs, patches/tests/0001-Workaround-to-make-a-run-make-test-pass.patch
Fix rust-lang/rustc_codegen_gcc#538.
=> Reenable run-make tests

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, build_system/src/build.rs, build_system/src/clean.rs, build_system/src/clone_gcc.rs, build_system/src/config.rs, build_system/src/fmt.rs, build_system/src/fuzz.rs, build_system/src/fuzz/reduce.rs, build_system/src/info.rs, build_system/src/prepare.rs, build_system/src/rust_tools.rs, build_system/src/test.rs, build_system/src/utils.rs, src/builder.rs, src/intrinsic/llvm.rs, src/type_.rs, tests/lang_tests_common.rs
Fixes rust-lang/rustc_codegen_gcc#712.
Fix the following warnings:
```
warning: unused variable: `curr`
--> src/fuzz/reduce.rs:42:13
|
42 |     let mut curr = 0;
|             ^^^^ help: if this is intentional, prefix it with an underscore: `_curr`
|
= note: `#[warn(unused_variables)]` on by default
warning: variable does not need to be mutable
--> src/fuzz/reduce.rs:42:9
|
42 |     let mut curr = 0;
|         ----^^^^
|         |
|         help: remove this `mut`
|
= note: `#[warn(unused_mut)]` on by default
warning: unused `Result` that must be used
--> src/fuzz/reduce.rs:431:9
|
431 |         out.write_all(line.as_bytes());
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: this `Result` may be an `Err` variant, which should be handled
= note: `#[warn(unused_must_use)]` on by default …
```
=> Fix fuzz warnings and deny warnings by default in build system

build_system/src/abi_test.rs
Slienced some bogus clippy warnings in `abi_tests`. 
This file is meant to be expanded in the future(by adding options needed for CI runs), and clippy is complaing about some of that scafolding code. 
The warning `clippy::never_loop` is raised because the command only supports one argument(`--help`) which stops argument parsing, and prints a message. So, the loop can only iterate once: by either printing the help, or an error message(for invalid options). This is correct, and the loop is still needed to handle new parameters we will add in the future.
`clippy::while_let_on_iterator`, on the other hand, warns us that this `while` loop could be rewritten as a `for` loop. This is true now, because we don't have any parameters with additional arguments. If we want to add a parameter like …
=> Fixed some clippy warnings.

src/builder.rs, src/context.rs
This PR updates the `create_type` and `Builder::load` functions to not call `get_aligned` when not necessary(for byte-sized types). It also contains some minor improvements to the comments in `Builder::load` function.
=> Skip needless calls to get_align in some cases.

src/intrinsic/mod.rs
All uses of the `current_func` field of `Context` in `Builder` can be safely replaced with `Builder::current_func`. This is done in preparation for removal of that field. 
Only one use of `current_func` remains - within `const_undef`, which is a function of `Context`, and not `Builder`.
=> Remove unnecesary uses of the 'current_func' field, replacing it with  a call to function.

src/lib.rs
This explicitly disables multithreading in `cg_gcc`. `libgccjit` is not thread-safe, and this option should not have been accidentally enabled in the first place.
=> Change the implementation of supports_parallel to signal tha cg_gcc is not thread safe.

src/builder.rs
Fixes rust-lang/rustc_codegen_gcc#717
=> Inserted a local variable in volatile_load, to ensure reads don't move across blocks.

build_system/src/fmt.rs, tests/run/int.rs, tests/run/int_overflow.rs, tests/run/structs.rs, tests/run/volatile.rs, tests/run/volatile2.rs
This PR addresses the run formatter on the `tests/run` directory of rust-lang/rustc_codegen_gcc#670
=> Fmt tests run

build_system/src/prepare.rs, build_system/src/utils.rs
This PR always pass the `user.name`, `user.email`, `core.autocrlf` and `commit.gpgSign` git parameters to the `run_command` and `run_command_with_output` functions.
With this PR, I managed to successfully run `./y.sh prepare` after a `./y.sh clean all" with and without `user.name` and `user.email` parameters defined for the repo.
Fixes rust-lang/rustc_codegen_gcc#731
=> Always add git user info to run_command
