- src/back/write.rs
> Fix asm output

- gcc-test-backend/src/main.rs
- src/base.rs
> Improve codegen but enabling -fno-semantic-interposition

- src/asm.rs
- tests/run/asm.rs
Fixes #109
CC @Commeownist just in case.
> Fix discarded in-out constraint in inline asm

- src/builder.rs
Updates the internal calls to `<Builder as BuilderMethods>::load` so that its `ty` parameter has consistent semantics, enabling this method's implementation to make use of it.
> Use the provided pointee type in `<Builder as BuilderMethods>::load`

- .github/workflows/ci.yml
- test.sh
Fixes https://github.com/rust-lang/rustc_codegen_gcc/issues/194.
> Split tests to have faster CI

- .github/workflows/ci.yml
> Download libgccjit-12-dev package in the CI

- Cargo.lock
- src/attributes.rs
Depends on https://github.com/antoyo/gcc/pull/18 and on https://github.com/antoyo/gccjit.rs/pull/12.
> Add support for cold attribute

- Cargo.lock
- Readme.md
- failing-ui-tests.txt
- src/base.rs
- src/lib.rs
> Add support for detecting CPU features

- Cargo.lock
- src/attributes.rs
Depends on https://github.com/antoyo/gcc/pull/20 and https://github.com/antoyo/gccjit.rs/pull/19.
> Add support for "returns_twice" function attribute

- Cargo.lock
- src/attributes.rs
Depends on https://github.com/antoyo/gcc/pull/21 and on https://github.com/antoyo/gccjit.rs/pull/20.
It'll also require to update gccjit-rs dependency once https://github.com/antoyo/gccjit.rs/pull/20 is merged.
> Add support for "pure" function attribute

- src/asm.rs
- tests/run/asm.rs
> Fix const handling in ATT syntax

- src/base.rs
> Handle static relocation model

- .github/workflows/stdarch.yml
- build_system/src/clean.rs
- build_system/src/test.rs
> Rename `y.sh test --clean-ui-tests` to `y.sh clean ui-tests`

- tests/failing-ui-tests.txt
- tests/failing-ui-tests12.txt
> Renable intrinsics-integer.rs test

- src/context.rs
> Fix check for main function already declared

- src/context.rs
> Fix panic when calling get_fn for a variable

- src/type_.rs
- tests/failing-ui-tests.txt
> Implement more type kinds

- .github/workflows/release.yml
Fixes #591 
I fixed based on the comments. It seems the previous PR was deleted when I synced the repository today
> Add grep check for LTO Test

- build_system/src/config.rs
> Fix `--use-system-gcc` option handling

- .github/workflows/ci.yml
Context: https://github.com/rust-lang/team/pull/1648
> Add CI success job
